"""Initial

Revision ID: 71bc38a6c99f
Revises: 
Create Date: 2025-07-04 16:31:45.706822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71bc38a6c99f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_name', sa.String(length=100), nullable=False),
    sa.Column('fruit_name', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vehicle_no', sa.String(length=20), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('total_lungar', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('board_no', sa.String(length=20), nullable=True),
    sa.Column('quality', sa.String(length=50), nullable=True),
    sa.Column('bill_no', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farmer_purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farmer_purchase_bill_no'), ['bill_no'], unique=True)

    op.create_table('seller_sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=False),
    sa.Column('quality', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('total_commission', sa.Float(), nullable=True),
    sa.Column('labour_charge', sa.Float(), nullable=True),
    sa.Column('mandi_charge', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('seller_sale')
    with op.batch_alter_table('farmer_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farmer_purchase_bill_no'))

    op.drop_table('farmer_purchase')
    # ### end Alembic commands ###
